language: cpp

matrix:
  include:
    - os: linux
      compiler: g++
    - os: linux
      compiler: clang
    - os: osx
      compiler: g++
    - os: osx
      compiler: clang

script: mkdir build && cd build && cmake .. && cmake --build .

branches:
 only:
  - master
  - dev

dist: trusty
install: true

notifications:
  email: false