version: 1.0.{build}
branches:
  only:
  - master
  - dev
configuration:
- Debug
- Release
platform: Any CPU
build_script:
- ps: >-
    mkdir build

    cd build

    cmake ..

    cmake --build . --config $env:CONFIGURATION
test_script:
- ps: ctest -V